### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by JakeHenshall** [braph/pyEbaySniper#1]
Hey,

When I run the file I get this message.

    File "pyEbaySniper.py", line 193
        command, *arguments = l.split()
                           ^
    SyntaxError: invalid syntax

It's pointing at the asterisk.

Thanks Jake.

**Comment by braph** [comment]
Hello,

I think you get that error because you are running the script with Python2.
Try to explicitly start it with Python3 using `python3 ./pyEbaySniper`

regards, Benjamin

**Comment by JakeHenshall** [comment]
Hey,

Thanks for the response.

I'm now getting this error:

    Traceback (most recent call last):
        File "pyEbaySniper.py", line 27, in <module>
            import requests
    ImportError: No module named 'requests'

Thanks Jake
